package App.Services;

public enum FileStatus {
    SUCCESS,
    INVALID_FILE,
    FILE_NOT_FOUND,
    EMPTY_FILE,
    INVALID_CONTENT,
    INCORRECT_MAGIC_BYTES,
    INCORRECT_EXTENSION,
    MAX_CAPACITY,
    FILE_NO_SELECTED,
    DANGEROUS_FILENAME,
    ALREADY_UPLOADED
}
